name: ttkapp
description: "The TTKApp™"
publish_to: 'none'
version: 0.0.1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter 
  intl: any
  geolocator: ^13.0.2
  path: ^1.9.0
  path_provider: ^2.0.15
  sqflite: ^2.4.1
  wakelock_plus: ^1.2.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - lib/core/database/sql/init/
    - lib/core/database/sql/create/
    - lib/core/database/sql/refresh/